modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
#issueTrackerURL="https://github.com/dashkal16/an_dims/issues/"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    logoFile="${mod_icon}"
    authors="${mod_author}"
    description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[${version_ars_nouveau},2)"
    ordering="NONE"
    side="BOTH"

